export interface Customer {
  Id: number;
  CustomerName: string;
  FirstName: string | null;
  LastName: string | null;
  PhoneNumber: string;
  GuestPhoneNumber: string | null;
  OTP: string | null;
  Email: string | null;
  City: string | null;
  Address: string | null;
  CreatedOnUTC: string;
  RequestedOn: string | null;
  RequestedOnLocalTime: string;
  PhoneNumberVerified: boolean;
  LoadLimit: number | null;
  ReferredBy: string | null;
  CreatedName: string;
  CreatedBy: string | null;
  Source: string;
  PlantId: number | null;
  PlantName: string;
  NOC: string;
  ForPlantDetails: string | null;
  PoleId: number | null;
  PoleNumber: string;
  ForPole: string | null;
  PoleIdDetails: number;
  DistanceFromPole: number | null;
  VerifiedRemarks: string | null;
  ConvertedRemarks: string | null;
  RejectedRemarks: string | null;
  AppointmentOn: string;
  Status: string;
  OperationRemarksStatus: string | null;
  StatusWithDate: string | null;
  VerifiedBy: string | null;
  VerifiedOn: string;
  VerifiedUser: string | null;
  ConvertedBy: string | null;
  ConvertedOn: string | null;
  ConvertedUser: string | null;
  RejectedBy: string | null;
  RejectedOn: string | null;
  RejectedUser: string | null;
  RegisteredType: string | null;
  Search: string | null;
  MeterAddedStatus: string | null;
  CustomerAddedStatus: string | null;
  RechargeStatus: string | null;
  AppointmentRemarks: string | null;
  TariffId: number | null;
  MeterSerial: string | null;
  ASMRemarks: string | null;
  OtherASMRemarks: string | null;
  CustomerDetails: string;
  CustomerId: number | null;
  CashPaymentId: number | null;
  CustomerAdditionStatus: string | null;
  StartDate: string | null;
  EndDate: string | null;
  PlantList: any[];
  PoleList: any[];
  StatusList: any[];
  ASMRemarksList: any[];
  HasFinalStatusPermission: boolean;
  HasRejectStatusPermission: boolean;
  HasAppointmentStatusPermission: boolean;
  HasASMRemarksPermission: boolean;
  HasVerifiedStatusPermission: boolean;
  HasConvertedStatusPermission: boolean;
  HasAddToCustomerPermission: boolean;
  HasOperationRemarksPermission: boolean;
  HasOperationStatusPermission: boolean;
  IsOperationRemarkPermissionUserRole: boolean;
  IsExistingCustomer: boolean;
  OperationRemarks: string | null;
  OperationStatus: string | null;
  CustomerBVN: string | null;
  SignupForm: string | null;
  HouseAddress: string | null;
  NumberofHouseholdMembers: number | null;
  IncomeLevel: string | null;
  LGA_Community: string | null;
  Identification_Type: string | null;
  Upload_Identification_Copy: string | null;
  NextofKinName: string | null;
  RelationshipWithNextofKin: string | null;
  PhoneNoofNextofKin: string | null;
  Occupation: string | null;
  PictureofReceiptPayment: string | null;
  Religion: string | null;
  Latitude: number | null;
  Longitude: number | null;
  CountryCode: string | null;
}