import { Customer } from "./interface/Customer";

const generateCustomer = (i: number): Customer => ({
  Id: 1000 + i,
  CustomerName: `Customer ${i}`,
  FirstName: null,
  LastName: null,
  PhoneNumber: `+91${9000000000 + i}`,
  GuestPhoneNumber: null,
  OTP: null,
  Email: null,
  City: null,
  Address: null,
  CreatedOnUTC: new Date().toISOString(),
  RequestedOn: null,
  RequestedOnLocalTime: new Date().toLocaleString(),
  PhoneNumberVerified: true,
  LoadLimit: i % 2 === 0 ? 100 : 200,
  ReferredBy: null,
  CreatedName: `Admin${i % 5}`,
  CreatedBy: null,
  Source: "User",
  PlantId: null,
  PlantName: `Plant ${i % 10}`,
  NOC: `NOC ${i % 3}`,
  ForPlantDetails: null,
  PoleId: null,
  PoleNumber: "",
  ForPole: null,
  PoleIdDetails: 0,
  DistanceFromPole: 50,
  VerifiedRemarks: "Verified",
  ConvertedRemarks: null,
  RejectedRemarks: null,
  AppointmentOn: "",
  Status: i % 3 === 0 ? "Converted" : i % 3 === 1 ? "Rejected" : "Pending",
  OperationRemarksStatus: null,
  StatusWithDate: null,
  VerifiedBy: null,
  VerifiedOn: new Date().toISOString(),
  VerifiedUser: null,
  ConvertedBy: null,
  ConvertedOn: null,
  ConvertedUser: null,
  RejectedBy: null,
  RejectedOn: null,
  RejectedUser: null,
  RegisteredType: null,
  Search: null,
  MeterAddedStatus: null,
  CustomerAddedStatus: null,
  RechargeStatus: null,
  AppointmentRemarks: null,
  TariffId: null,
  MeterSerial: null,
  ASMRemarks: null,
  OtherASMRemarks: null,
  CustomerDetails: "New",
  CustomerId: null,
  CashPaymentId: null,
  CustomerAdditionStatus: "Pending",
  StartDate: null,
  EndDate: null,
  PlantList: [],
  PoleList: [],
  StatusList: [],
  ASMRemarksList: [],
  HasFinalStatusPermission: false,
  HasRejectStatusPermission: false,
  HasAppointmentStatusPermission: false,
  HasASMRemarksPermission: false,
  HasVerifiedStatusPermission: false,
  HasConvertedStatusPermission: false,
  HasAddToCustomerPermission: false,
  HasOperationRemarksPermission: false,
  HasOperationStatusPermission: false,
  IsOperationRemarkPermissionUserRole: false,
  IsExistingCustomer: false,
  OperationRemarks: null,
  OperationStatus: null,
  CustomerBVN: null,
  SignupForm: null,
  HouseAddress: null,
  NumberofHouseholdMembers: null,
  IncomeLevel: null,
  LGA_Community: null,
  Identification_Type: null,
  Upload_Identification_Copy: null,
  NextofKinName: null,
  RelationshipWithNextofKin: null,
  PhoneNoofNextofKin: null,
  Occupation: null,
  PictureofReceiptPayment: null,
  Religion: null,
  Latitude: null,
  Longitude: null,
  CountryCode: null,
});

// Main data mock
export const Data: { Data: Customer[] } = {
  Data: Array.from({ length: 5000 }, (_, i) => generateCustomer(i)),
};
