# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Build and deploy to Azure Web App

env:
  AZURE_WEBAPP_NAME: huskneuron-v2-ui-qa

on:
  push:
    branches:
      - premission_check

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  build:
    name: 'Build and Push to ACR'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_URL }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Docker Build and Push (with VITE env as build-arg)
        run: |
          docker build \
            --build-arg VITE_APP_CUSTOMER360URL=${{ secrets.VITE_APP_CUSTOMER360URL }} \
            -t huskifyacr.azurecr.io/huskneuronv2-qa:${{ github.sha }} .
          docker push huskifyacr.azurecr.io/huskneuronv2-qa:${{ github.sha }}

  deploy:
    name: 'Deploy to QA'
    runs-on: ubuntu-latest

    needs: build

    environment:
      name: 'QA'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.QA_AZUREWEBAPPPUBLISHPROFILE }}
          images: huskifyacr.azurecr.io/huskneuronv2-qa:${{ github.sha }}